<div class="pages">
	<center><h1>SELAMAT DATANG DI SITUS PARA PECINTA MUSIK ROCK</h1></center><br>
	<center><img src="images/rs-234712-GettyImages-80557019.jpg" width="700px" height="400px"></center>
	<br>
	<p>		Musik rok (bahasa Inggris: rock) adalah genre musik populer yang mulai diketahui secara umum pada pertengahan tahun '50-an. Akarnya berasal dari rhythm and blues, musik country dari tahun '40 dan '50-an serta berbagai pengaruh lainnya. Selanjutnya, musik rok juga mengambil gaya dari berbagai musik lainnya, termasuk musik rakyat (folk music), jazz dan musik klasik.[1]</p>

	<p>		BBunyi khas dari musik rok sering berkisar sekitar gitar listrik atau gitar akustik, dan penggunaan back beat yang sangat kentara pada rhythm section dengan gitar bass dan drum, dan kibor seperti organ, piano atau sejak '70-an, synthesizer. Di samping gitar atau kibor, saksofon dan harmonika bergaya blues kadang digunakan sebagai instrumen musik solo. Dalam bentuk murninya, musik rok "mempunyai tiga chords, backbeat yang konsisten dan mencolok dan melodi yang menarik".</p>

	<p>		Pada akhir tahun '60-an dan awal '70-an, musik rok berkembang menjadi beberapa jenis. Yang bercampur dengan musik folk (musik daerah di Amerika) menjadi folk rock, dengan blues menjadi blues-rock dan dengan jazz, menjadi jazz-rock fusion. Pada tahun '70-an, rock menggabungkan pengaruh dari soul, funk, dan musik latin. Juga pada tahun '70-an, rock berkembang menjadi berbagai subgenre (subkategori) seperti soft rock, glam rock, heavy metal, hard rock, progressive rock, dan punk rock. Subkategori rock yang mencuat pada tahun '80-an termasuk New Wave, hardcore punk, dan alternative rock. Pada tahun '90-an terdapat grunge, Britpop, indie rock dan nu metal.</p>

	<p>		Sebuah kelompok pemusik yang mengkhususkan diri memainkan musik rok dijuluki rock band atau rock group (grup musik rok). Rock group banyak yang terdiri dari pemain gitar, penyanyi utama (lead singer), pemain gitar bass, dan drummer (pemain drum), membentuk sebuah quartet. Beberapa group menanggalkan satu atau dua posisi di atas dan/atau menggunakan pennyanyi utama sebagai pemain alat musik di samping menyanyi, membentuk duo atau trio. Grup lainnya memiliki pemusik tambahan seperti dua rhythm gitar dan atau seorang keyboardist (pemain kibor). Agak lebih jarang, penggunaan alat musik bersenar seperti biola, cello, atau alat tiup seperti saksofon, trompet, atau trombon.</p>
</div>